; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName          "WebRadio"
#define MyAppVersion       GetVersionNumbersString('..\..\WebRadio\bin\Release\Publish\WebRadio.exe')
#define MyAppPlatform      "64bit"
#define MyAppPublisher     "Exploitox"
#define MyAppURL           "https://github.com/valnoxy/WebRadio"
#define MyAppExeName       "WebRadio.exe"
#define MyAppStartingYear  "2018"
#define MyAppEndingYear    GetDateTimeString('yyyy','','')
              
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{61F70E73-5493-43E1-B777-D8587E3B5EF9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion} ({#MyAppPlatform})
AppMutex=valnoxyWebRadio

VersionInfoDescription={#MyAppName} Installer
VersionInfoVersion={#MyAppVersion}
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
AppCopyright=Copyright © {#MyAppStartingYear} - {#MyAppEndingYear} {#MyAppPublisher}. All rights reserved.

AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
AppPublisher={#MyAppPublisher}

WizardStyle=modern
SetupIconFile=..\..\WebRadio\Assets\WebRadio.ico
ShowLanguageDialog=yes
UsePreviousLanguage=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
UsePreviousAppDir=yes
DisableProgramGroupPage=yes
LicenseFile=..\..\LICENSE.md
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=..\Output
OutputBaseFilename=WebRadio_{#MyAppVersion}_x64
Compression=lzma2/ultra64
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\WebRadio\bin\Release\Publish\*"; DestDir: "{app}"; Excludes: "*.pdb"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runasoriginaluser

[Code]
procedure DeleteAutoStartEntry;
var
  RegKey: string;
begin
  RegKey := 'Software\Microsoft\Windows\CurrentVersion\Run';
  RegDeleteValue(HKEY_CURRENT_USER, RegKey, 'WebRadio');
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ConfigDir, ConfigPath: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    DeleteAutoStartEntry;

    ConfigDir := ExpandConstant('{userappdata}\valnoxy\WebRadio');
    ConfigPath := ConfigDir + '\config.json';
    if not FileExists(ConfigPath) then
      Exit;

    if UninstallSilent then
      Exit;

    if MsgBox('Do you also want to remove your WebRadio settings and station list?',
              mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
    begin
      DeleteFile(ConfigPath);
      RemoveDir(ConfigDir);
      RemoveDir(ExpandConstant('{userappdata}\valnoxy'));
    end;
  end;
end;